name: main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/master'}}
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, can-fail: true, runner: windows-2022 },
          { msystem: MINGW32, can-fail: true, runner: windows-2022 },
          { msystem: UCRT64, can-fail: true, runner: windows-2022 },
          { msystem: CLANG64, can-fail: true, runner: windows-2022 },
          # { msystem: CLANGARM64, can-fail: true, runner: ['Windows', 'ARM64'] }
        ]
    name: ${{ matrix.msystem }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Gather Facts
        id: facts
        run: |
          Get-PSDrive -PSProvider FileSystem | Format-Table -AutoSize -Wrap
          Get-CIMInstance -Class Win32_Processor | Select-Object -Property Name
          Get-CIMInstance Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum | Format-Table @{n="TotalPhysicalMemory";e={$_.Sum}}

      - name: Configure Pagefile
        # https://github.com/al-cheb/configure-pagefile-action/issues/16
        continue-on-error: true
        uses: al-cheb/configure-pagefile-action@9b6da52fb72a3c6147c1aad2df22d8d905681adc # v1.5
        with:
          minimum-size: 4GB
          maximum-size: 16GB
          # Needs to be C:, see https://github.com/al-cheb/configure-pagefile-action/issues/18
          disk-root: "C:"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: temp
          fetch-depth: 0
          filter: blob:none
          persist-credentials: false

      - uses: msys2/setup-msys2@cafece8e6baf9247cf9b1bf95097b0b983cc558d # v2.31.0
        with:
          msystem: ${{ matrix.msystem }}
          install: git python base-devel
          update: true
          location: 'D:\M'

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          cp /etc/pacman.conf /etc/pacman.conf.bak
          grep -qFx '[staging]' /etc/pacman.conf || sed -i '/^# \[staging\]/,/^$/ s|^# ||g' /etc/pacman.conf

      - name: Update using staging
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: Move Checkout
        run: |
          If (Test-Path "C:\_") { rm -r -fo "C:\_" }
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CI-Build
        shell: msys2 {0}
        continue-on-error: ${{ matrix.can-fail }}
        id: build
        run: |
          cd /C/_
          if [[ "$MSYSTEM" != "${{ matrix.msystem }}" ]]; then
            MSYSTEM=${{ matrix.msystem }}
            set +e
            . shell ${MSYSTEM,,}
            set -e
          fi
          MINGW_ARCH=${{ matrix.msystem }} ./.ci/ci-build.sh

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ matrix.msystem }}
          artifacts: C:/_/artifacts/*.pkg.tar.*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Clean up runner"
        if: ${{ always() }}
        continue-on-error: true
        run: |
          If (Test-Path "C:\_") { rm -r -fo "C:\_" }
          msys2 -c 'mv -f /etc/pacman.conf.bak /etc/pacman.conf'
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
